### ISSUE TITLE
latest release does not record any cassettes

### ISSUE THREAD

**Issue by darrenleeweber** [ktosiek/pytest-vcr#22] opened 2019-05-03 18:10 UTC
## versions
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

$ poetry --version
Poetry 0.12.11

$ pip freeze | grep vcr
pytest-vcr==1.0.2
vcrpy==2.0.1

$ pip freeze | grep pytest
pytest==4.4.1
pytest-cov==2.7.1
pytest-forked==1.0.2
pytest-mock==1.10.4
pytest-ordering==0.6
pytest-runner==4.4
pytest-vcr==1.0.2
pytest-xdist==1.28.0
```

Removed all `tests/cassettes` and ran `pytest --vcr-record=all` to replace all the cassettes, but there's no output cassettes and all the tests that should record cassettes are passing.  There no custom configuration settings and tests use the basic `@pytest.mark.vcr()` decorators.

```
$ pytest --fixtures

----------------------------------------------------------------------------- fixtures defined from pytest_vcr ------------------------------------------------------------------------------
vcr_config
    Custom configuration for VCR.py
vcr
    The VCR instance
vcr_cassette
    Wrap a test in a VCR.py cassette
vcr_cassette_dir
    .venv/lib/python3.7/site-packages/pytest_vcr.py:92: no docstring available
vcr_cassette_name
    Name of the VCR cassette
```

**Comment by ktosiek** [comment] 2019-05-03 18:22
Thank you for the report! Which version are you upgrading from?

**Comment by darrenleeweber** [comment] 2019-05-03 18:28
Prior working versions might have been (from git commit on Pipfile.lock):
```
pytest==4.02
pytest-vcr==1.0.1
vcrpy==2.0.1
```

**Comment by ktosiek** [comment] 2019-05-03 18:53
That is strange, especially if downgrade did not help. Do you use unittest.TestCase? Can you:
- extract a small example of a test that fails to generate a cassette?
- make sure the tests actually run, by putting a failing assertion after the code that should get recorded by VCR?

**Comment by darrenleeweber** [comment] 2019-05-03 19:14
```python
# all the library imports are good, plus:
import pytest

@pytest.mark.vcr()
def test_fetch_json_with_site_string(dates):
    site = "01115183"
    q = USGSClient.query(site, dt_start=dates.begin, dt_end=dates.end, data_format='json')
    response = USGSClient.fetch(q)
    check_json_response(response)
```

```
$ pytest --vcr-record=all tests/test_usgs_fetch.py -k 'test_fetch_json_with_site_string'
============ test session starts ====================
platform linux -- Python 3.7.2, pytest-4.0.2, py-1.8.0, pluggy-0.9.0
rootdir: /home/joe/src/jupiter/usgs-water-services, inifile: pytest.ini
plugins: requests-mock-1.6.0, xdist-1.27.0, vcr-1.0.1, ordering-0.6, mock-1.10.4, forked-1.0.2, cov-2.7.1
collected 6 items / 5 deselected                                                                                                                                                            

tests/test_usgs_fetch.py .                                                                                                                                                            [100%]
```

```
$ cat pytest.ini 
[pytest]
log_format = %(asctime)s - %(name)-12s - %(levelname)-8s - %(message)s
log_date_format = %Y-%m-%d %H:%M:%S

filterwarnings =
    module::DeprecationWarning
```
With or without that `pytest.ini` file, the behavior is the same.  The `tests/cassettes` directory is the same before/after, i.e.
```
tests/
├── cassettes
```

**Comment by darrenleeweber** [comment] 2019-05-03 19:29
```toml
# pyproject.toml snippets

[tool.poetry.dependencies]
python = "^3.7"
lxml = "^4.3"
numpy = "*"
OWSLib = "^0.17.0"
pandas = "^0.24.0"
pytz = "*"
pyyaml = "*"
requests = "^2.0"
scipy = "*"
urllib3 = "*"

[tool.poetry.dev-dependencies]
alabaster = "*"
black = {version = "^18.3-alpha.0", allows-prereleases = true}
codecov = "*"
docutils = "*"
"flake8" = "*"
"flake8-type-annotations" = "*"
freezegun = "*"
ipdb = "*"
ipython = "*"
invoke = "*"
invoke-release = "*"
pylint = "^2.3"
pytest = "^4.0"
pytest-cov = "*"
pytest-mock = "*"
pytest-ordering = "*"
pytest-runner = "*"
pytest-vcr = "*"
pytest-xdist = "*"
requests_mock = "*"
sphinx = "^2.0"
tox = "*"
detox = "*"
twine = "^1.0"
yapf = "*"
wheel = "*"
```

**Comment by darrenleeweber** [comment] 2019-05-03 19:33
`Removing lxml (4.3.3)` and the cassettes are back again.  Issue resolved, sorta.
```
$ tree tests/
tests/
├── cassettes
│   ├── test_fetch_json_to_data_frames.yaml
│   ├── test_fetch_json_with_site_string.yaml
│   ├── test_fetch_json.yaml
│   └── test_iana.yaml
```

```
$ pip freeze | grep pytest
pytest==4.4.1
pytest-cov==2.7.1
pytest-forked==1.0.2
pytest-mock==1.10.4
pytest-ordering==0.6
pytest-runner==4.4
pytest-vcr==1.0.2
pytest-xdist==1.28.0
```

**Comment by ktosiek** [comment] 2019-05-04 10:56
Can you reproduce the issue after adding lxml back? If not, I'll write this off as some kind of bit flip for now.

If anyone else sees a similar problem **please comment**. I couldn't reproduce the problem, but any additional details might help.

**Comment by darrenleeweber** [comment] 2019-05-06 21:46
Still works after adding `lxml` back (got `4.3.3` again).

/shrug

**Comment by ktosiek** [comment] 2019-05-07 04:06
Closing this issue until the problem comes back.

**Closed by ktosiek** 2019-05-07 04:06 UTC

**Comment by alex-hsp** [comment] 2019-12-12 15:39
I had the simial problem. 

My actual http requests were made in a fixture that was used by test marked with vcr. So it seems like vcr was not able to see any requests made from fixture. So i had to to is to manuall wrap with `vcr.use_cassette` in my fixture.

**Comment by neozenith** [comment] 2019-12-12 16:20
We had a similar problem but after running `pytest --setup-only --setup-show` We figured out that one of the fixtures we expected to be recorded was at the class level and the vcr cassette was only getting mounted at the function level. 

The cassette only gets mounted at function level (for recording or replay) to maintain test isolation so each can run in parallel. 

We split the fixture so that some setup was class level but the part that needed to be recorded with each test was function level scopes fixtures. 

Started working.
